"""
core/database.py — Async MongoDB connection using Motor driver.
Provides collection getters used throughout the application.
"""

from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase
from loguru import logger
from typing import Optional

from core.config import settings


class DatabaseManager:
    """
    Singleton database manager that holds the Motor client.
    Initialized on FastAPI startup and closed on shutdown.
    """

    client: Optional[AsyncIOMotorClient] = None
    db: Optional[AsyncIOMotorDatabase] = None

    async def connect(self) -> None:
        """Open Motor async connection to MongoDB."""
        logger.info(f"Connecting to MongoDB at {settings.MONGODB_URL}")
        self.client = AsyncIOMotorClient(
            settings.MONGODB_URL,
            serverSelectionTimeoutMS=5000,  # 5 second connection timeout
            maxPoolSize=50,  # connection pool size
        )
        self.db = self.client[settings.DATABASE_NAME]

        # Verify connection by pinging the server
        await self.client.admin.command("ping")
        logger.info(f"Connected to MongoDB — database: '{settings.DATABASE_NAME}'")

    async def disconnect(self) -> None:
        """Close Motor connection cleanly."""
        if self.client:
            self.client.close()
            logger.info("MongoDB connection closed.")


# Module-level singleton
db_manager = DatabaseManager()


# ─── Collection accessors ─────────────────────────────────────────────
# Use these in routers and services; never access db_manager.db directly.


def get_tickets_collection():
    """Support tickets — core data store."""
    return db_manager.db["tickets"]


def get_users_collection():
    """Users (customers, agents, admins)."""
    return db_manager.db["users"]


def get_feedback_collection():
    """Agent feedback used for model retraining."""
    return db_manager.db["feedback"]


def get_audit_logs_collection():
    """Full immutable audit trail of every AI decision."""
    return db_manager.db["audit_logs"]


def get_root_cause_alerts_collection():
    """Incident spike alerts generated by root cause engine."""
    return db_manager.db["root_cause_alerts"]


def get_knowledge_articles_collection():
    """Auto-generated knowledge base articles."""
    return db_manager.db["knowledge_articles"]


def get_model_versions_collection():
    """Model training history and performance metrics."""
    return db_manager.db["model_versions"]


def get_db() -> AsyncIOMotorDatabase:
    """Direct DB accessor (use specific collection getters when possible)."""
    return db_manager.db


async def create_indexes() -> None:
    """
    Create MongoDB indexes on startup for query performance.
    Called once from main.py lifespan handler.
    """
    db = db_manager.db

    # Tickets: common query patterns
    await db["tickets"].create_index("ticket_id", unique=True)
    await db["tickets"].create_index("user_id")
    await db["tickets"].create_index("status")
    await db["tickets"].create_index("created_at")
    await db["tickets"].create_index([("ai_analysis.category", 1), ("status", 1)])
    await db["tickets"].create_index(
        [("ai_analysis.routing_decision", 1), ("status", 1)]
    )

    # Users: lookup by email (unique) and role
    await db["users"].create_index("email", unique=True)
    await db["users"].create_index("user_id", unique=True)
    await db["users"].create_index("role")

    # Feedback: link to tickets and training status
    await db["feedback"].create_index("ticket_id")
    await db["feedback"].create_index("used_for_retraining")
    await db["feedback"].create_index("timestamp")

    # Audit logs: ticket linkage and chronology
    await db["audit_logs"].create_index("ticket_id")
    await db["audit_logs"].create_index("timestamp")
    await db["audit_logs"].create_index("model_version")

    # Root cause alerts: open incidents by category
    await db["root_cause_alerts"].create_index([("status", 1), ("category", 1)])
    await db["root_cause_alerts"].create_index("timestamp")

    # Knowledge articles: search and usage ranking
    await db["knowledge_articles"].create_index("category")
    await db["knowledge_articles"].create_index(
        [("usage_count", -1)]  # most-used first
    )
    await db["knowledge_articles"].create_index(
        [("title", "text"), ("tags", "text")]  # full-text search
    )

    # Model versions: find active model quickly
    await db["model_versions"].create_index("is_active")
    await db["model_versions"].create_index("trained_at")

    # Security: threat level and escalation queries
    await db["tickets"].create_index("ai_analysis.threat_level")
    await db["tickets"].create_index("ai_analysis.threat_type")
    await db["tickets"].create_index("is_escalated")
    await db["escalation_logs"].create_index("ticket_id")
    await db["escalation_logs"].create_index([("acknowledged", 1), ("resolved", 1)])
    await db["escalation_logs"].create_index("severity")
    await db["escalation_logs"].create_index("created_at")

    logger.info("MongoDB indexes created successfully.")
